### ISSUE TITLE
WebUI dashboard information

### ISSUE THREAD

**Issue by kelsos** [raiden-network/webui#10]
As we previously discussed it would be good to replace the home page of the webui with some dashboard. 

I was thinking that faucet #2465 for the testnet version could go in the dashboard. Along with maybe information about the account funds. Other than this we could also display information about the number of open channels, maybe joined networks or total deposits in channels etc.

I would like your input and feedback on what information you think would be helpful to have in the dashboard as a user of the webui.

**Comment by manuelwedler** [comment]
accomplished by redesign #253
