### ISSUE TITLE
Increase minted token amount

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#133]
At the moment when clicking the mint button the user receives 1000 tokens (non decimal notation). After applying the decimals the amount is below the displayed decimal places for common tokens. Besides that minting takes long.
It would be nice to get a bigger amount of tokens, e.g. 0.01 tokens.

**Comment by czepluch** [comment]
Came here to file an issue for this too. Would be great to increase the amount to something like 0.001.

**Comment by kelsos** [comment]
@czepluch That is why we opened the issue. Since it takes a while for the tokens to get minted the 1000 wei amount is small. If you want to get a nice testing amount it would take way to long.

**Comment by czepluch** [comment]
I don't understand this. Are you saying that it takes longer to mint a big amount? Can't we just change the default minting behavior to be a higher amount? Or am I misunderstanding you comment @kelsos ?

**Comment by manuelwedler** [comment]
He meant that it takes long if you click repeatedly on the mint button to get a big amount.
So yes changing the amount to a higher value is possible.

**Comment by czepluch** [comment]
Alright. Then we agree :)
