### ISSUE TITLE
Upgrade to Angular 8.x

### ISSUE THREAD

**Issue by kelsos** [raiden-network/webui#134]
Angular 8.x has been released for a while now.
 
I did try to upgrade to the 8.0 milestone before, but there were some performance issues after upgrading, so the work has never been merged.

Since there have been some minor version upgrades we should try upgrading again.
If after upgrading there are no performance issues with the WebUI we proceed with the upgrade.

For help on the upgrade process please have a look [here](https://update.angular.io/)

**Comment by manuelwedler** [comment]
So I tried to upgrade. It works for the core, but updating angular material gives a peer dependencies incompatibility error. Seems to be an issue of the Angular CLI: https://github.com/angular/angular-cli/issues/14980
