### ISSUE TITLE
Paginator does not fit screen width on small mobile screens

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#139]
## Describe the bug
The paginator used on the tokens and channels page does not fit the screen width on small mobile screens.

## Screenshots
On 360x640 screen:
![Screen Shot 2019-08-14 at 09 38 58](https://user-images.githubusercontent.com/34456797/63002965-6c5e0f00-be77-11e9-8faf-4e6b1232d6dd.png)

## System:
- Firefox 68.0.1 web dev tools
 - WebUI v0.9.2

**Comment by kelsos** [comment]
@manuelwedler I tried to fix it at least twice. :'(
