### ISSUE TITLE
UI improvements ideas/feedback

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/webui#14]
Couple of tiny things I've noticed and some improvement ideas. 

- [x] display eth balance in the webui. Rationale: user needs gas to interact with the contracts and it'd be nice to know how much funds he has left
- [ ] display warning if eth balance is below $LIMIT
- [x] PAY dialog: if receiver field is empty, it would be nice to present a list of known receivers
- [ ] Channels: display (online/offline) status of the partner. Or just gray out PAY button.
- [ ] display correct balance if payment is pending
- [ ] clicking partner's avatar could update partner's status (send ping or something)
- [ ] when placing the cursor in the Amount field of the PAY dialog, default value of zero should be cleared. 
- [ ] open payment history (or last X payments) by clicking on the channel rectangle - it's a frequently used feature, it shouldn't be hidden in the menu
- [x] clicking blue circle with a number in the top right corner should display past messages (sometimes they disappear without user noticing)
- [ ] Enter should submit dialogs (see PAY and DEPOSIT)
- [x] After doing deposit, the message "channel has been modified with deposit of X" is confusing. It should display something like "new channel balance: X"

**Comment by manuelwedler** [comment]
I split this issue into separate issues for every feature/improvement which has not been implemented yet. For some were already existing issues.

2. #193 
4. #202
5. #206 (needs discussion)
6. the status would be automatically updated if implemented as in raiden-network/raiden#2016
7. #203
8. #204
10. #205
