### ISSUE TITLE
PAY for a specific token network lists all available tokens in the "Select Token" dropdown

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/webui#141]
## Describe the bug
When the user clicks PAY for a specific token network a list of all available tokens is provided even though it is only possible to make payments with the token network the user is connected with.

## Steps to reproduce
1. Go to the 'Tokens' screen
2. Click on 'PAY' (after having joined a token network)
3. Scroll down to 'Select Token'
4. See error (a list of tokens for all available token networks)

## Expected behavior
The expected behavior is for it to only be the token networks the user is connected with available as an option when making payments.

## System:
 - WebUI [v0.7.1] If you use the bundled version you can skip the WebUI version

**Comment by manuelwedler** [comment]
Is the 'Select Token' field not filled with the token network address already for you? So you would actually not need to fill that field.

**Comment by taleldayekh** [comment]
Yes, it is pre-filled for me as well but it is a bit confusing that I'm given the option to choose from a list of tokens that are not compatible with the token network I'm using.

**Comment by manuelwedler** [comment]
If you select another token there you would send the payment in the network, that belongs to the other token. So there is no compatibility issue here.

We could disable the field if it is prefilled. Maybe that would be less confusing for the user.
@kelsos Any opinions on that?

**Comment by kelsos** [comment]
The problem is that for pay you also have the tokens that are not connected
listed.

When I am not part of the a token network I cannot send to a node I the
network since I have no channels for the said token network.

I remember having a scenario though where all of them should be listed. I
am not 100% about the specifics but it  should be in the history.
