### ISSUE TITLE
Show token network funds

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#142]
At the moment it is not possible to see how much funds you have put in a token network. When joining a network not all of the funds are immediately allocated to a channel. It would be helpful to the user to see the amount of funding that was put into the network.

**Comment by kelsos** [comment]
@manuelwedler really nice idea, but is it exposed through the API?

**Comment by manuelwedler** [comment]
Yes, the `/connections` endpoint gives this information.

**Comment by manuelwedler** [comment]
accomplished by redesign #253
