### ISSUE TITLE
RPC error screen not working

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#146]
## Describe the bug
The WebUI is supposed to show an error screen if the RPC connection fails. At the moment it is stuck at the loading screen in that case. The error screen should be shown.

## System:
- WebUI v0.9.2

**Comment by kelsos** [comment]
@manuelwedler Thanks for opening the issue. 

To ensure this works properly you have to run a local version of Geth & Raiden but not allow the WebUI on Geth's CORS settings.
