### ISSUE TITLE
Easy faucet in the web ui

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/webui#15]
Add a button in the webui which will request ether tokens for the current running account when the node is connected to a test network, this should make testing easier for new accounts.

**Comment by kelsos** [comment]
Adding a button that directly requests from the faucet might not be possible, but we can expose a link to the faucet that changes depending on the test network, and gets removed when the WebUI is on mainnet. 
[Walleth](https://github.com/walleth) does something similar in the network selection screen.

**Comment by kelsos** [comment]
@manuelwedler 

Requirements
- Works at each network except mainnet.
- Faucet link could be added to as a new property to `Network` https://github.com/raiden-network/webui/blob/ad4ce8b158c8ebc7e9486984a193040697af3bd2/src/app/utils/network-info.ts#L46
- Button should probably on the header/toolbar
- It should open the faucet URL in a new page, with the user's address prefilled when possible (Görli/Ropsten faucet)
