### ISSUE TITLE
Inform the user about the current in-flight payments

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/webui#16]
## Problem Definition

if a payment takes too long a user may try a second time, unaware the previous has not completed yet, which may result in the same payment being made twice. To avoid this the UI should:

- [x] Inform the user about the current payments which are in-flight
- [ ] Ask for a confirmation if the user tries a second payment for the same target and value is tried.

**Comment by kelsos** [comment]
@manuelwedler It seems that the api we needed for these has been merged for half a year now let's talk next week on what we need to do on that.

**Comment by manuelwedler** [comment]
Alright!
