### ISSUE TITLE
WebUI docs shows localhost with wrong port (5000), links correct port (5001)

### ISSUE THREAD

**Issue by mat7ias** [raiden-network/webui#177]
## Describe the bug
[Run the Raiden Web Application](https://docs.raiden.network/the-raiden-web-interface#run-the-raiden-web-application) in the Raiden docs has the correct link if clicked, although shows the wrong port (5000 instead of 5001): 
"Once you have a Raiden node up and running the WebUI will be available on [http://localhost:5000](http://localhost:5001)."

## Expected
"Once you have a Raiden node up and running the WebUI will be available on [http://localhost:5001](http://localhost:5001)."

**Comment by taleldayekh** [comment]
Thank you, fixed it! :)
