### ISSUE TITLE
ENS resolution hangs if network not supported by Web3

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#179]
## Describe the bug
If the used network is not supported for ENS by Web3, the loading circle, which is shown while resolving an ENS name besides the address input field of the payment dialog, stays for ever. The validity won't get updated if a valid address is put in afterwards. The payment dialog has to be reopened in that case.

This is printed in the console:
```
ERROR TypeError: "ENS is not supported on network: "private""
    _callee3$ web3-eth-ens.umd.js:1056
    tryCatch runtime.js:45
    invoke runtime.js:271
    method runtime.js:97
    asyncGeneratorStep asyncToGenerator.js:3
    _next asyncToGenerator.js:25
    Angular 13
core.js:6014:19
```

## Expected behavior
An error should be shown below the input field if ENS is not supported for the used network.

## Screenshots
![Selection_009](https://user-images.githubusercontent.com/34456797/66836150-1eda4d00-ef61-11e9-9603-b878cd7ec628.png)

## System
- Raiden: v0.200.0rc1
- WebUI: v0.10.0
- Environment: development
- Network: Görli
- User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by kelsos** [comment]
@manuelwedler I had this in mind but forgot to create an issue about that.

Since we have the network information, we could add a flag like `ens` there and disable ens support completely on the unsupported networks. 

Is that close to what you had in mind too?

**Comment by kelsos** [comment]
Yes if ens is not supported it would make sense to have an instant error message.
