### ISSUE TITLE
`Payment in flight` pending action does not get removed from notification panel

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#181]
## Describe the bug
Sometimes the `Payment in flight` pending action won't get removed from the notification panel after the payment succeeds or fails.

## Expected behavior
If the payment succeeds or fails the pending action should get removed.

## Screenshots
![Selection_010](https://user-images.githubusercontent.com/34456797/67092288-2131e680-f1af-11e9-9a2a-1b98d7fa0e27.png)

## System
- Raiden: v0.200.0rc1
- WebUI: v0.10.0
- Environment: development
- Network: Görli
- User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by kelsos** [comment]
@manuelwedler are you caching the notifications in local storage or they are just kept in memory?

**Comment by manuelwedler** [comment]
They are just kept in memory.
