### ISSUE TITLE
Show symbol/name of token on the incoming notification

### ISSUE THREAD

**Issue by kelsos** [raiden-network/webui#185]
Currently, the incoming payment notification looks like this:
![image](https://user-images.githubusercontent.com/2269732/68590836-bf079100-048f-11ea-8d24-ccc7686a69d6.png)

It would be really nice if along with the address we somehow also could show the token name and/or symbol.

**Comment by manuelwedler** [comment]
@kelsos Have you used the bundled version with the latest RC? I think I already implemented this. Should be in the v0.10.1 release of the WebUI.

**Comment by kelsos** [comment]
@manuelwedler I am pretty certain this was with the latest RC, but let me have a look again to verify. Sorry for being lazy, it seems I forgot to include the version. (I was the one who insisted that adding the copy button would make it easier for people to include version information... :man_facepalming:)

**Comment by kelsos** [comment]
@manuelwedler 
It seems that the last RC uses 0.10.0 of the WebUI so I cam losing the issue since this is already done. Sorry.

```
## System
- Raiden: v0.200.0rc1
- WebUI: v0.10.0
- Environment: development
- Network: Görli
- User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```
