### ISSUE TITLE
Store token information for Mainnet tokens

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#230]
On mainnet it is currently not possible to register new token networks. Considering that there will only be WETH and DAI for Alderaan, we could store the information of the tokens as constants in the WebUI. So it would not be necessary to make the Web3 calls for them. Additionally we could add the official logos for those tokens and display them.

**Comment by kelsos** [comment]
I am not sure if this is overkill or not but there is https://github.com/MetaMask/eth-contract-metadata/
