### ISSUE TITLE
Update docs to redesign

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#257]
### Description
The web interface tutorial in the documentation guides through the old WebUI. It should be updated to guide through the redesigned WebUI.

### Tasks
- [x] Update documentation
- [x] Review by @taleldayekh 
- [x] Update README

**Comment by kelsos** [comment]
@taleldayekh we should also probably need to make a new video. Since the one in the README is of the old WebUI.

**Comment by manuelwedler** [comment]
https://docs.raiden.network/the-raiden-web-interface is updated
