### ISSUE TITLE
Balance Update notification is very vague

### ISSUE THREAD

**Issue by BOR4** [raiden-network/webui#337]
**Is your feature request related to a problem? Please describe.**
As a fairly inexperienced user I rely on notifications to better understand what is going on with my Raiden node. I noticed both when I deposited to channel and when I received payment there was same notification.

**Describe the solution you'd like**
More specific notification describing what exactly caused balance update

![image](https://user-images.githubusercontent.com/40821065/79503299-36d67a80-8031-11ea-926c-6f99daf9224d.png)

I attached a screen shot here 0.5 is me depositing to channel and other payment is what I received. Both show same description.

**Comment by manuelwedler** [comment]
Thank you for the feedback! We already fixed this issue in the unreleased redesign (see #232).
