### ISSUE TITLE
Dialog allows me to try send negative amount ... shows nice error message when it fails

### ISSUE THREAD

**Issue by BOR4** [raiden-network/webui#339]
## Expected behavior

Disable "Send" if amount is negative and maybe additionally make it red (like for amount=0 and random non number input)

## Screenshots

![image](https://user-images.githubusercontent.com/40821065/79505351-89656600-8034-11ea-957c-9f15f30b3c87.png)

## System:
Linux, mozilla, RC7

**Comment by manuelwedler** [comment]
Thanks for opening this issue!
