### ISSUE TITLE
Use the new status endpoint in the Raiden API

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/webui#341]
**Is your feature request related to a problem? Please describe.**
Synching Raiden might take a while and the user might not know, why he cannot use raiden.

**Describe the solution you'd like**
Show a progress bar

**Describe alternatives you've considered**

**Additional context**
Raiden Issue: https://github.com/raiden-network/raiden/issues/5281

**Comment by manuelwedler** [comment]
Good that this is finally implemented. We had the redesign of the loading screen already in mind (#266)
