### ISSUE TITLE
Host redesigned WebUI

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#346]
### Description
It would be nice to have a hosted version of the redesign, so it can already be tested.

**Comment by kelsos** [comment]
@manuelwedler Probably creating a tag on docker for this would also make things easier for that @eorituz

**Comment by manuelwedler** [comment]
Demonodes are hosted here:
https://node1.demonode.raiden.network/
https://node2.demonode.raiden.network/
https://node3.demonode.raiden.network/

**Comment by eorituz** [comment]
User: heiko
Password: hees
