### ISSUE TITLE
Design feedback main screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/webui#379]
**Is your feature request related to a problem? Please describe.**
- I cannot read some parts of the text.
- The big blue "button" consistently pulls my attention and outshines the other parts of the screen (especially the grey fonts).
- The transaction history is more important to me 

**Describe the solution you'd like**
- Smallest font size should be at least 12px (looked at the smallest font in github as a reference)
- Make the big blue "button" white like the "Make transfer" button or make it a ghost "button"
- Reduce the height of the Token Network "button"
- Move the transaction history below the token "button" and the contacts to the right

**Describe alternatives you've considered**
- Just make "Select Network" a button and show the token amount and name below in white.

**Additional context**

![grafik](https://user-images.githubusercontent.com/35398162/81079903-72f25200-8ef0-11ea-95dd-fec8f5ed84dc.png)

CC @sashseurat

**Comment by sashseurat** [comment]
discussed feedback with Christian and Manuel, redesigned draft and reviewed with Manuel
<iframe style="border: none;" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FQfuxB5LBXFZblu4YNKReGX%2FWebUI-Iteration-9%3Fnode-id%3D157%253A83%26scaling%3Dmin-zoom" allowfullscreen></iframe>

**Comment by christianbrb** [comment]
Looks great, thanks :) 👍
