### ISSUE TITLE
Improve sidebar

### ISSUE THREAD

**Issue by CosminNechifor** [raiden-network/webui#4]
## Feature request

In the UI if you press ``Esc`` the side menu on the left will disappear and there is no other way to bring it back, without refreshing the page. 

E.q:

![before_esc](https://user-images.githubusercontent.com/22676160/48546232-7e068c00-e8d0-11e8-86d9-8d4b6dc0f2c0.png)
![after_esc](https://user-images.githubusercontent.com/22676160/48546234-7f37b900-e8d0-11e8-8137-83dbaf6df3d1.png)

## Solution

Make it possible when we click on the logo to bring it back.

**Comment by manuelwedler** [comment]
Since PR #151 the side menu is not closable by `ESC` anymore. I don't see a benefit to have it closable. Besides it would not be intuitive for the user to click the Raiden logo for toggling the menu.
Closing due to this.
