### ISSUE TITLE
WebUI should allow you to open a channel without any balance

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/webui#41]
I tried to open a channel without any balance and the webui does not let me. This should just work. Any idea why it is currently not allowed?

![2019-01-01-164731_556x464_scrot](https://user-images.githubusercontent.com/1658405/50574263-14413380-0de5-11e9-9ab7-44c016df7fb9.png)

**Comment by kelsos** [comment]
@LefterisJP there is a validation requiring the channel balance to be more than zero, I don't remember if that was there before or if I inserted it due to erroneous assumptions but it should be an easy fix though.
