### ISSUE TITLE
Show warning for small transfer amounts

### ISSUE THREAD

**Issue by palango** [raiden-network/webui#432]
**Is your feature request related to a problem? Please describe.**

With mediation fees transfers of small amounts may fail when the transfer is mediated. This was unintuitive for testers and we should try to warn that that might happen.

See https://github.com/raiden-network/raiden/issues/6188

**Describe the solution you'd like**

When sending a transfer from the UI we have an input. We should check the value of that input and display a warning if the amount is smaller than a limit. 

Ideally this limit depends on the token, if this is too hard, use a general limit. The warning should not be shown for other tokens (e.g. on testnets)

The warning might read like:
> The amount of your transfer is below the limit for mediated payments. We recommend an amount of at least LIMIT if you are not using a direct channel. See https://docs.raiden.network/using-raiden/mediation-fees for more information on this topic.

`LIMIT` should be 
- DAI: 10^-5 DAI (10^13 in DAI wei)
- WETH: 10^-7 W-ETH (10^11 in WETH wei)

**Describe alternatives you've considered**

Disallowing transfers below that limit, but that seems to hard.

**Additional context**

The maximum amount of fees relative to the payment amount is 20%
The default fees are:
- Flat fee
  - DAI: 10^12
  - WETH: 10^10
- Proportional: 0,4%
- Imbalance: 0,3%

This leads to this equation:
https://www.wolframalpha.com/input/?i=1.2+x+%3E+%28x%2B10%5E12%29*1.003

We round this up and get
- DAI: 10^13
- WETH: 10^11

**Comment by Dominik1999** [comment]
https://github.com/raiden-network/webui/pull/434

**Comment by manuelwedler** [comment]
We decided to also implement this for the new WebUI to be able to release it next week.
