### ISSUE TITLE
Testing the new WebUI

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/webui#433]
## Our nice new WebUI must be tested for one week
The new WebUI should be tested for one week starting at the 01. of June. The test should end at the 05. of June with daily check-ins and if needed adjustments. We might need two testers.

## Prerequisites for testing
- [x] find two testers
- [x] define test cases
- [x] distribute tokens for mainnet testing 

## Suggested procedure
- [x] test on Goerli and link issues found
- [x] test on mainnet and link issues found
- [x] final wrap up

**Comment by GataKamsky** [comment]
@czepluch & @agatsoh can you help with testing this once the Alderaan release is out?

**Comment by czepluch** [comment]
Sure, would be happy to

**Comment by agatsoh** [comment]
Same here would like to test the new webui

**Comment by czepluch** [comment]
Draft for things to test: https://docs.google.com/spreadsheets/d/1gMBqd7H-DHjN7gpfP484BGpO3LLjXgXVz3jCmuIfCso/edit#gid=0

**Comment by czepluch** [comment]
We need to define a clear goal for testing. Should it focus on UX or just testing the functionalities of the webui and make sure that all functionality of Raiden is supported?

**Comment by czepluch** [comment]
We only test functionality

**Comment by czepluch** [comment]
Testing went well. We have one issue created here: https://github.com/raiden-network/webui/issues/456

The testing results can be seen here:
https://docs.google.com/spreadsheets/d/1gMBqd7H-DHjN7gpfP484BGpO3LLjXgXVz3jCmuIfCso/edit#gid=853196588
