### ISSUE TITLE
Content-Type header not set to application/json

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/webui#476]
## Describe the bug
The `Content-Type` header of our POST and PUT requests is set to `text/plain`. 
v1.0.0 of Raiden was not complaining of the wrongly set header. The new v1.0.1 client returns `{"errors":"JSON payload expected"}` in that case. So all POST and PUT requests are failing from the WebUI.

I couldn't find what commit caused this change in the client, but this should get fixed in the WebUI anyway.

## Expected behavior
The `Content-Type` header of our POST and PUT requests should get set to `application/json`. 

## System
- Raiden: v1.0.1
- WebUI: v1.0.0
- Environment: development
- Network: Görli
- User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

**Comment by Dominik1999** [comment]
Thank you for finding this! Why was this bug not found last week during testing? did we change anything?

**Comment by manuelwedler** [comment]
We tested last week on v1.0.0. There must be a change afterwards that leads to this bug.

**Comment by palango** [comment]
It was probably caused by https://github.com/raiden-network/raiden/pull/6246 .
