### ISSUE TITLE
Add explanation about how to do UDC deposit

### ISSUE THREAD

**Issue by czepluch** [raiden-network/webui#535]
It would be nice to have a link or tooltip that tells people what to do when they have no UDC deposit. Currently no information is given about how to move forward.

![Screenshot from 2020-09-02 15-45-50](https://user-images.githubusercontent.com/1026799/91991840-b68c8980-ed33-11ea-86d2-7b374c4ad152.png)

**Comment by manuelwedler** [comment]
I would rather have the possibility to deposit directly from the WebUI, but this could be a quick fix. Maybe there is time for it after the wizard testing.

**Comment by czepluch** [comment]
Yes, that would be ideal

**Comment by manuelwedler** [comment]
#556 is being implemented at the moment. So no need for this.
