### ISSUE TITLE
UI for all payments/all payments per token

### ISSUE THREAD

**Issue by palango** [raiden-network/webui#6]
## Abstract

We should provide a way in the webUI to show the payment history in general or filtered by token.

## Motivation

Currently the webUI only display the payment history for a given token and partner pair. But one might want to see all payments in a given token network.
Furthermore by clicking in the UI I can only see the history with direct channel partners, which hides all mediated transfers.

## Specification

Provide webUI for
- [x] The whole payment history
- [x] The payment history for a given token network
- [x] a way to show payment history with arbitrary receivers

## Backwards Compatibility

None, all the endpoints are already there.

**Comment by manuelwedler** [comment]
accomplished by redesign #253
