### ISSUE TITLE
Improve dialogues for pending channel openings and deposits

### ISSUE THREAD

**Issue by franzihei** [raiden-network/webui#82]
When opening a new channel and depositing the initial deposit into the channel, I am missing a notification that keeps me updated about what is happening. e.g. a pop-up dialogue window on the top right confirming "Opening channel with [target address] has been initiated" and updating me once the channel has been successfully opened and the deposit is in the channel.

Also, it would be nice to get an estimate on how long this might take or at least notify me that it's an on-chain transaction and can take some time.

**Comment by manuelwedler** [comment]
The PR #169 will add a toast notification for initiated actions like the channel opening. There are already toasts implemented for the successful opening and deposit events.

For the notification that on-chain transactions take time, I created an follow-up issue: #170
