### ISSUE TITLE
Mark the balance as `awaiting` for newly opened channels while the deposit is pending

### ISSUE THREAD

**Issue by franzihei** [raiden-network/webui#83]
## Problem 
Currently, (on Kovan testnet) I can see newly opened channels with a balance of 0, before (after waiting another couple of seconds/minutes), the deposit shows up in the channel. This is confusing since the deposit was already gone from the balance in the "token overview" page, but wasn't shown in the channel deposit yet, meaning that for a short period of time that deposit is nowhere to be seen.

## Solution Proposal 
One could only show the newly opened channel once the deposit has been added to the channel, too and not before that. This would take away the confusion that the deposit is gone from the token balance, but not yet in the channel. The process could be supported with update notifications see #82.

**Comment by czepluch** [comment]
But a deposit is not mandatory. You can open channels without depositing to them. And these channels should still be shown.

**Comment by franzihei** [comment]
Yes, true. One could specify this for the cases in which I open a channel and deposit. 

Currently, if I open a channel and add a deposit it's very confusing to have the deposit amount deducted from the balance immediately (in the token overview page) and not shown anywhere for a certain amount of time. A user should, at all times, be ables to see all of their funds somewhere.

**Comment by manuelwedler** [comment]
I decided with @Dominik1999 to put an `awaiting` in place of the balance for channels that were created with balance > 0 and have their deposit pending.
While the action is pending the deposit amount is shown in the notification panel.
