### ISSUE TITLE
Add link to readthedocs WebUI documentation and YouTube Video

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/webui#84]
**Is your feature request related to a problem? Please describe.**
- How to use the WebUI is not within this repository

**Describe the solution you'd like**
Links in the Readme to:
- https://raiden-network.readthedocs.io/en/latest/webui_tutorial.html
- https://www.youtube.com/watch?v=ASWeFdHDK-E&t=5s (Maybe embedded)

**Describe alternatives you've considered**

**Additional context**

**Comment by kelsos** [comment]
@christianbrb I was thinking that the README needs some update, there are also some outdated sections.
The [template](https://github.com/othneildrew/Best-README-Template) that you told be about should be a good starting point. I will go through and update it using this and I will add the links to the video and tutorial there.
